/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class filters3d_ */

#ifndef _Included_filters3d_
#define _Included_filters3d_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     filters3d_
 * Method:    jniMean3D
 * Signature: ([[BIIIIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMean3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniTopHat3D
 * Signature: ([[BIIIIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniTopHat3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniTopHat3D_16
 * Signature: ([[SIIIIII)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniTopHat3D_116
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMean3D_16
 * Signature: ([[SIIIIII)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMean3D_116
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMedian3D
 * Signature: ([[BIIIIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMedian3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMedian3D_16
 * Signature: ([[SIIIIII)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMedian3D_116
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMinimum3D
 * Signature: ([[BIIIIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMinimum3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMinimum3D_16
 * Signature: ([[SIIIIII)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMinimum3D_116
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     filters3d_
 * Method:    jniMaximum3D
 * Signature: ([[BIIIIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMaximum3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMaximumLocal3D
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);
/*
 * Class:     filters3d_
 * Method:    jniMaximum3D_16
 * Signature: ([[SIIIIII)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_filters3d_1_jniMaximumLocal3D_116
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
